# Generated by Django 4.1.4 on 2022-12-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('T', 'Trabalho'), ('E', 'Estudo'), ('L', 'Lazer')], default='T', max_length=1)),
                ('status', models.CharField(choices=[('N', 'Não Iniciada'), ('E', 'Em Andamento'), ('F', 'Finalizada')], default='N', max_length=1)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
